export default [
  { firstName: "Aida", country: "fr", githubUsername: "AidaBej", gender: "female" },
  { firstName: "Aimée", country: "fr", githubUsername: "aimeestone", gender: "female" },
  { firstName: "Alexandre", country: "fr", githubUsername: "Alexandre2590", gender: "male" },
  { firstName: "Anais", country: "fr", githubUsername: "anaislor", gender: "female" },
  { firstName: "Antonin", country: "fr", githubUsername: "gramsco", gender: "male" },
  { firstName: "Doro", country: "de", githubUsername: "DoriDoro", gender: "female" },
  { firstName: "Henri", country: "be", githubUsername: "belke05", gender: "male" },
  { firstName: "Julie", country: "fr", githubUsername: "juliecarra", gender: "female" },
  { firstName: "Justine", country: "fr", githubUsername: "Juddorange", gender: "female" },
  { firstName: "Loup", country: "fr", githubUsername: "Loupiaut", gender: "male" },
  { firstName: "Margaux", country: "fr", githubUsername: "MargauxGibert15", gender: "female" },
  { firstName: "Niraja", country: "np", githubUsername: "niraja426", gender: "female" },
  { firstName: "Sadri", country: "fr", githubUsername: "sadrisellami", gender: "male" },
  { firstName: "Sara", country: "fr", githubUsername: "SebHacker", gender: "female" },
  { firstName: "Sophie-Anne", country: "fr", githubUsername: "sophieannebourgine", gender: "female" },
  { firstName: "Xavier", country: "fr", githubUsername: "SandwichExpert", gender: "male" },
];